### ISSUE TITLE
add more angular version compatibility to all libraries

### ISSUE THREAD

**Issue by ddurham2** [umutyerebakmaz/ngx-bio-components#345]
Might it be possible for you to declare a more permissive version range on peerDependencies?  Otherwise, it's a problem for a project that isn't on the exact same version of angular to depend on your component.

For example... 
https://github.com/umutyerebakmaz/ngx-bio-components/blob/3ea6354a64ac8037dc7341fab9c4ecde07bb7ce2/libs/button/package.json#L21

Could it depend on something like `^15`  rather than an exact version?  Is that syntax supported at that point in the package.json?

Currently, I must use npm install -f , or fork your project.

Thanks

**Comment by umutyerebakmaz** [comment]
Hi, @ddurham2 of course, I have overlooked my corrections and new package release as soon as possible. Thank you very much for your attention.

**Comment by ddurham2** [comment]
Hi @umutyerebakmaz,

Thanks so much for making a release.  However, while mostly fixed, there's still a pegged version.  You can see on
    https://www.npmjs.com/package/@ngx-bio-components/button?activeTab=code -> package.json -> line 24
that while @angular/core and @angular/common are now fixed, it still references @angular/cdk to "15.2.8" instead of "^15.2.8"

I looked at the code in the repo, and it all seems correct, but somehow the produced output is not correct.  Could be something in the build cache that needs to be cleared out and fully rebuilt?

Thanks again

---

Update: I think it's because @angular/cdk needs to be listed as a peer dependency in button's package.json (perhaps needed in tooltip as well?).  Otherwise, it's just using what got installed

**Comment by umutyerebakmaz** [comment]
Hi @ddurham2 , I'll look at it as soon as possible, I've been very busy lately. Thank you for your return.
